### ISSUE TITLE
Creation de la table engrenage

### ISSUE THREAD

**Issue by brmuloot** [brmuloot/Musee_engrenages#1]
Ajouter une table à la base de donnée nommé flaskr qui se situe dans le fichier instance. Créer cette table à partir d'un code en .sql. Pour cela utiliser le fichier schema.sql disponible dans le dossier flaskr. La table engrenage devra contenir : 

-_name_, la **clé primaire** référant au nom de l'engrenage
-_advanage_, un texte qui contiendra les avantages de l'engrenage
-_drowback_, un texte qui contiendra les désavantage de l'engrange
-_image_, l'image de l'engrenage que l'on souhaiteras afficher sur le site
-_descr_, une description rapide de l'engrenage

**Comment by brmuloot** [comment]
exemple de création d'une table :

CREATE TABLE IF NOT EXISTS transaction (
    nom VARCHAR(32) NOT NULL,
    nomEquipe VARCHAR(32),
    date DATETIME,
    lieu VARCHAR(32),
    prix FLOAT(32),
    PRIMARY KEY (nom)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by brmuloot** [comment]
/!\ J'ai oublié de te dire il faut aussi ajouter attribute _auteur_ qui se referent au nom de la personne qui l'a ajouté /!\

**Comment by Kewseray** [comment]
Création de table sql engrenage
