### ISSUE TITLE
Insérer les données dans engrenages

### ISSUE THREAD

**Issue by brmuloot** [brmuloot/Musee_engrenages#2]
Tu vas insérer les données des engrenages présent dans la doc dans la table engrenage. Tu vas devoir enregistrer les images du site et les mettres dans un dossier, afin que tu puisse rentrer dans la colonne image le chemin vers les images depuis ton pc. Bon courage !

**Comment by brmuloot** [comment]
exemple d'insertion de donnée en .sql :

INSERT INTO transaction (nom, nomEquipe, date, lieu, prix) VALUES 
('AXA SA', 'equipe1', '2021-06-15', 'PARIS', 26),
('TotalEnergies', 'equipe2', '2004-09-03', 'PARIS', 57),
('Apple Inc', 'equipe1', '2014-09-05', 'USA', 150),
('Dubai Elec', 'equipe3', '2020-11-22', 'DUBAI', 1),
('Amazon', 'equipe3', '2010-07-12', 'USA', 100),
('Naspers', 'equipe2', '1997-08-16', 'SOUTH AFRICA', 120),
('PetroChina', 'equipe5', '2019-04-20', 'HONG KONG', 10),
('ETF Vanguard','equipe7', '2015-02-22', 'LA', 200),
('Dassault Aviation', 'equipe6', '2016-01-01', 'PARIS', 140);

**Comment by brmuloot** [comment]
Tu les ajouteras à la suite du dossier schemas.sql

**Comment by brmuloot** [comment]
update il faut que tu stock les images dans le dossier static !

**Comment by Kewseray** [comment]
-Les images stocké dans le dossier static.
-Les données des engrenages inséré dans la table engrenage.

**Comment by Kewseray** [comment]
-Les images ajoutés dans la table engrenage.
